export const world_capitals_by_continent = {
  europe: [
    "Warszawa",
    "Paryż",
    "Berlin",
    "Madryt",
    "Rzym",
    "Londyn",
    "Moskwa",
    "Amsterdam",
    "Sztokholm",
  ],
  africa: ["Dakar", "Kair", "Lagos", "Johannesburg", "Nairobi"],
  asia: [
    "Tokio",
    "Pekin",
    "Delhi",
    "Mumbaj",
    "Seul",
    "Bangkok",
    "Dżakarta",
    "Rijad",
    "Istambuł",
  ],
  north_america: [
    "Waszyngton",
    "Ottawa",
    "Meksyk",
    "Hawana",
    "Kanada",
    "Nowy Jork",
    "Los Angeles",
    "Toronto",
    "Chicago",
  ],
  south_america: [
    "Brasília",
    "Buenos Aires",
    "Lima",
    "Bogota",
    "Santiago",
    "Caracas",
    "Rio de Janeiro",
    "Asunción",
    "Montevideo",
  ],
  australia: [
    "Canberra",
    "Sydney",
    "Melbourne",
    "Brisbane",
    "Adelaide",
    "Perth",
    "Wellington",
    "Auckland",
  ],
};
